/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.tallerpoo.gui;

import edu.tallerpoo.data.LogicaTriage;
import java.awt.Color;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;

/**
 * Esta clase de la pantalla de cambiar triage
 * 
 */
public class CambiarTriage extends javax.swing.JFrame {

    /**
     * Creates new form CambiarTriageNew
     */
    public CambiarTriage() {
        initComponents();
    }
    
    private int cambio;
    
    private String[] paciente;
    
    public void setPaciente(String[] paciente){
        this.paciente=paciente;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Niveles = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        colorBarra = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosNuevosTabla = new javax.swing.JTable();
        Cancelar = new javax.swing.JButton();
        motivoText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Confirmar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        apellidoLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();

        Niveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        javax.swing.GroupLayout colorBarraLayout = new javax.swing.GroupLayout(colorBarra);
        colorBarra.setLayout(colorBarraLayout);
        colorBarraLayout.setHorizontalGroup(
            colorBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        colorBarraLayout.setVerticalGroup(
            colorBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        datosNuevosTabla.setBackground(new java.awt.Color(238, 238, 238));
        datosNuevosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nivel", "Color", "Urgencia", "Tiempo Estimado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        datosNuevosTabla.setGridColor(new java.awt.Color(21, 21, 21));
        datosNuevosTabla.setSelectionBackground(new java.awt.Color(238, 238, 238));
        datosNuevosTabla.setSelectionForeground(new java.awt.Color(21, 21, 21));
        datosNuevosTabla.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datosNuevosTablaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(datosNuevosTabla);
        if (datosNuevosTabla.getColumnModel().getColumnCount() > 0) {
            datosNuevosTabla.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(Niveles));
        }

        Cancelar.setBackground(new java.awt.Color(5, 59, 80));
        Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar.setText("Cancelar Cambio");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Motivo de Cambio");

        jPanel2.setBackground(new java.awt.Color(100, 204, 197));

        jLabel1.setBackground(new java.awt.Color(100, 204, 197));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital Delicia Concepcion Masvernat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(23, 107, 135));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(23, 107, 135));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cambiar Triage");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(404, 404, 404))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel5.setText("Datos del Triage");

        Confirmar.setBackground(new java.awt.Color(5, 59, 80));
        Confirmar.setForeground(new java.awt.Color(255, 255, 255));
        Confirmar.setText("Confirmar Cambio");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("DNI:");

        jLabel7.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Apellido:");

        dniLabel.setText("jLabel4");

        nombreLabel.setText("jLabel9");

        apellidoLabel.setText("jLabel10");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("ID REGISTRO");

        idLabel.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(colorBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(motivoText, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(dniLabel))
                                .addGap(132, 132, 132)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(nombreLabel))
                                .addGap(116, 116, 116)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellidoLabel)
                                    .addComponent(jLabel8))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLabel)
                                    .addComponent(jLabel9))))
                        .addGap(175, 175, 175))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dniLabel)
                            .addComponent(nombreLabel)
                            .addComponent(apellidoLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idLabel)))
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(colorBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(motivoText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Confirmar))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    /**
     * Este metodo muestra el color, urgencia y el tiempo estimado de anencion en base a un nivel seleccionado
     * 
     * @param evt 
     */
    private void datosNuevosTablaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datosNuevosTablaPropertyChange
        try{
            String a=Niveles.getSelectedItem().toString();
            switch (a){
                case "1" -> {
                    colorBarra.setBackground(Color.red);
                    cambio=sumador(Integer.parseInt(Niveles.getSelectedItem().toString()));
                    datosNuevosTabla.setValueAt("ROJO",0,1);
                    datosNuevosTabla.setValueAt("RIESGO VITAL INMEDIATO",0,2);
                    datosNuevosTabla.setValueAt("ATENCION INMEDIATA",0,3);
                }
                case "2" -> {
                    colorBarra.setBackground(Color.orange);
                    cambio=sumador(Integer.parseInt(Niveles.getSelectedItem().toString()));
                    datosNuevosTabla.setValueAt("NARANJA",0,1);
                    datosNuevosTabla.setValueAt("MUY URGENTE",0,2);
                    datosNuevosTabla.setValueAt("10-15 MIN.",0,3);
                }
                case "3" -> {
                    colorBarra.setBackground(Color.yellow);
                    cambio=sumador(Integer.parseInt(Niveles.getSelectedItem().toString()));
                    datosNuevosTabla.setValueAt("AMARILLO",0,1);
                    datosNuevosTabla.setValueAt("URGENTE",0,2);
                    datosNuevosTabla.setValueAt("60 MIN.",0,3);
                }
                case "4" -> {
                    colorBarra.setBackground(Color.green);
                    cambio=sumador(Integer.parseInt(Niveles.getSelectedItem().toString()));
                    datosNuevosTabla.setValueAt("VERDE",0,1);
                    datosNuevosTabla.setValueAt("NORMAL",0,2);
                    datosNuevosTabla.setValueAt("2 HORAS",0,3);
                }
                case "5" -> {
                    colorBarra.setBackground(Color.blue);
                   cambio=sumador(Integer.parseInt(Niveles.getSelectedItem().toString()));
                    datosNuevosTabla.setValueAt("AZUL",0,1);
                    datosNuevosTabla.setValueAt("NO URGENTE",0,2);
                    datosNuevosTabla.setValueAt("4 HORAS",0,3);
                }
            }
        }
        catch (Exception e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_datosNuevosTablaPropertyChange
    /**
     * al precionar el boton "Cancelar Cambio" cierra la pantalla actual
     * 
     * @param evt 
     */
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed
    
    private int sumador(int x){
        LogicaTriage lt=new LogicaTriage();
        int suma=(Integer.parseInt(lt.nivel(idLabel.getText()))-(x));
        return suma;
    }
    
    
    
    
    /**
     * al precionar el boton "Confirmar Cambio" Este metodo actualiza en triage del paciente y cierra la pantalla actual
     * 
     * @param evt 
     */
    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        LogicaTriage lt=new LogicaTriage();
        int z;
        if (cambio<0){
            z=(cambio*-1);
        }else{
            z=cambio;
        }
        System.out.println(cambio);
        System.out.println(z);
        int nivelviejo=Integer.parseInt(lt.nivel(idLabel.getText()));
        System.out.println(nivelviejo);
        
        if (z>2){
            JOptionPane.showMessageDialog(this, "Solo pueden haber dos niveles de diferencia en el cambio", "", JOptionPane.ERROR_MESSAGE);
        }else{
        int opcion = JOptionPane.showOptionDialog( this,   "¿Está seguro que desea cambiar el triage?", "",  JOptionPane.YES_NO_OPTION,   JOptionPane.WARNING_MESSAGE, null, 
        new Object[]{"Sí", "No"}, 
         "Sí"); 
            if (opcion == JOptionPane.YES_OPTION) {
        lt.cambiarTriage(Integer.parseInt(idLabel.getText()), motivoText.getText(), Niveles.getSelectedItem().toString());
        JOptionPane.showMessageDialog(this, "Triage cambiado con exito", "", JOptionPane.WARNING_MESSAGE);
        this.dispose();
        }else if (opcion == JOptionPane.NO_OPTION) {
        }
      }                                         
        
    }//GEN-LAST:event_ConfirmarActionPerformed

    /**
     * Cuando se muestra la pantalla muestra los datos del paciente del cual se va a cambiar el triage.
     * 
     * @param evt 
     */
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        LogicaTriage lt=new LogicaTriage();
        dniLabel.setText(paciente[0]);
        nombreLabel.setText(paciente[1]);
        apellidoLabel.setText(paciente[2]); 
        idLabel.setText(paciente[3]);
        System.out.println(lt.nivel(idLabel.getText()));
        colorBarra.setBackground(lt.Color2(lt.nivel(idLabel.getText())));
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarTriage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarTriage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarTriage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarTriage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarTriage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Confirmar;
    private javax.swing.JComboBox<String> Niveles;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JPanel colorBarra;
    private javax.swing.JTable datosNuevosTabla;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField motivoText;
    private javax.swing.JLabel nombreLabel;
    // End of variables declaration//GEN-END:variables
}
