package edu.tallerpoo.gui;

import com.opencsv.exceptions.CsvValidationException;
import edu.tallerpoo.data.LogicaEstudioMedico;
import edu.tallerpoo.data.LogicaHistoriaClinica;
import edu.tallerpoo.data.Utilidades;
import edu.tallerpoo.model.HistoriaClinica;
import edu.tallerpoo.model.ResultadoEstudio;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Esta clase se encarga de mostrar los estudios clinicos
 */
public class EstudiosClinicos extends javax.swing.JFrame {
private Date fecha;
private Date hora;

    
    /**
     * Crea una instancia de la clase EstudiosClinicos con la fecha y hora seteadas.
     * 
     * @param fecha {@link Date}-Fecha que se realizo el estudio
     * @param hora  {@link Date}-Hora que se realizo el estudio
     */
    public EstudiosClinicos(Date fecha, Date hora) {
        this.fecha = fecha;
        this.hora = hora;
    }

    /**
     * Obtiene la fecha en la que se realizo el estudio clinico
     * 
     * @return {@link Date}-Fecha del estudio clinico
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * Establece la fecha en la que se ralizo el estudio clinico
     * 
     * @param fecha {@link Date}-Fecha del estudio clinico
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    
    /**
     * Obtiene la hora en la que se realizo el estudio clinico
     * 
     * @return {@link Date}-hora del estudio clinico
     */
    public Date getHora() {
        return hora;
    }

    /**
     * Establece la hora en la que se realizo el estudio clinico
     * 
     * @param hora {@link Date}-hora del estudio clinico
     */
    public void setHora(Date hora) {
        this.hora = hora;
    }

    /**
     * Actualiza la tabla de contenidos de la pantalla
     * 
     */
    public void actualizar(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        LogicaEstudioMedico estudios=new LogicaEstudioMedico();
        ArrayList<ResultadoEstudio> es = new ArrayList();

        try {
            es=estudios.leerCSVEstudioMedico();
        } catch (CsvValidationException ex) {
            Logger.getLogger(EstudiosClinicos.class.getName()).log(Level.SEVERE, null, ex);
        }





        for (ResultadoEstudio a : es) {
            String [] array={Integer.toString(a.getId()),Utilidades.convertDate(a.getFecha()),Utilidades.convertHora(a.getHora()),a.getTipoDeEstudio(),a.getInforme()};
           model.addRow(array);

        }
    }
    
    /**
     * Creates new form EstudiosClinicos
     */
    public EstudiosClinicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cerrarsesionbtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        InicioMedButton = new javax.swing.JButton();
        triagesButton = new javax.swing.JButton();
        PacientesMedButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        agregarEstudioButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        volverHistoriaButton = new javax.swing.JButton();
        actualizar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        jPanel2.setBackground(new java.awt.Color(100, 204, 197));

        jLabel1.setBackground(new java.awt.Color(100, 204, 197));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital Delicia Concepcion Masvernat");

        cerrarsesionbtn.setBackground(new java.awt.Color(5, 59, 80));
        cerrarsesionbtn.setForeground(new java.awt.Color(255, 255, 255));
        cerrarsesionbtn.setText("Cerrar Sesion");
        cerrarsesionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarsesionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cerrarsesionbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(23, 107, 135));

        InicioMedButton.setBackground(new java.awt.Color(5, 59, 80));
        InicioMedButton.setForeground(new java.awt.Color(255, 255, 255));
        InicioMedButton.setText("Inicio");
        InicioMedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioMedButtonActionPerformed(evt);
            }
        });

        triagesButton.setBackground(new java.awt.Color(5, 59, 80));
        triagesButton.setForeground(new java.awt.Color(255, 255, 255));
        triagesButton.setText("Pacientes");
        triagesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triagesButtonActionPerformed(evt);
            }
        });

        PacientesMedButton.setBackground(new java.awt.Color(5, 59, 80));
        PacientesMedButton.setForeground(new java.awt.Color(255, 255, 255));
        PacientesMedButton.setText("Pacientes en Espera");
        PacientesMedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacientesMedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InicioMedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(triagesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
            .addComponent(PacientesMedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(InicioMedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(triagesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PacientesMedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(23, 107, 135));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(23, 107, 135));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Estudios Clinicos");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Estudio Clinico", "Fecha", "Hora", "Tipo de Estudio", "Informe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        agregarEstudioButton.setBackground(new java.awt.Color(5, 59, 80));
        agregarEstudioButton.setForeground(new java.awt.Color(255, 255, 255));
        agregarEstudioButton.setText("Agregar Estudio Clinico");
        agregarEstudioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEstudioButtonActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(238, 238, 238));

        volverHistoriaButton.setBackground(new java.awt.Color(5, 59, 80));
        volverHistoriaButton.setForeground(new java.awt.Color(255, 255, 255));
        volverHistoriaButton.setText("Volver a Historia Clinica");
        volverHistoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverHistoriaButtonActionPerformed(evt);
            }
        });

        actualizar.setBackground(new java.awt.Color(5, 59, 80));
        actualizar.setForeground(new java.awt.Color(255, 255, 255));
        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(agregarEstudioButton)
                                .addGap(33, 33, 33)
                                .addComponent(actualizar)
                                .addGap(414, 414, 414)
                                .addComponent(volverHistoriaButton))
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarEstudioButton)
                            .addComponent(volverHistoriaButton)
                            .addComponent(actualizar))
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * al precionar el boton "cerrar sesion" Este metodo cierra la pantalla actual y abre la del login
     * @param evt 
     */
    private void cerrarsesionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionbtnActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_cerrarsesionbtnActionPerformed
   
    /**
     * al precionar el boton "inicio" Este metodo cierra la pantalla acutal y abre a la principar del medico
     * @param evt 
     */
    private void InicioMedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioMedButtonActionPerformed
        this.dispose();
        MedicoGUI m1 = new MedicoGUI();
        m1.setVisible(true);
        m1.setLocationRelativeTo(null);
    }//GEN-LAST:event_InicioMedButtonActionPerformed

    /**
     * al precionar el boton "Triages" Este metodo cierra la pantalla actual y muestra la de los pacientes que no tienen triage realizado
     * @param evt 
     */
    private void triagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triagesButtonActionPerformed
        this.dispose();
        Pacientes t1 = new Pacientes();
        t1.setVisible(true);
        t1.setLocationRelativeTo(null);
    }//GEN-LAST:event_triagesButtonActionPerformed

    /**
     * al precionar el boton "Pacientes en Espera" Este metodo cierra la pantalla acutal y abre la que tiene la lista de pacientes sin atender 
     * @param evt 
     */
    private void PacientesMedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacientesMedButtonActionPerformed
        this.dispose();
        PacientesAtencion p1 = new PacientesAtencion();
        p1.setVisible(true);
        p1.setLocationRelativeTo(null);
    }//GEN-LAST:event_PacientesMedButtonActionPerformed

    /**
     * al precionar el boton "Agregar Estudio Clinico" Este metodo abre la ventana para agregar un estudio clinico
     * @param evt 
     */
    private void agregarEstudioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEstudioButtonActionPerformed
        AgregarEstudioClinico et = new AgregarEstudioClinico();
        et.setVisible(true);
        et.setLocationRelativeTo(null);
       
        
    }//GEN-LAST:event_agregarEstudioButtonActionPerformed
    
    /**
     * al precionar el boton "Volver a Historia Clinica" Este metodo cierra la pantalla actual y muestra la que tiene las historias clinicas de los pacientes
     * @param evt 
     */
    private void volverHistoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverHistoriaButtonActionPerformed
        this.dispose();
        HistoriaClinicaPaciente p1 = new HistoriaClinicaPaciente();
        p1.setVisible(true);
        p1.setLocationRelativeTo(null);
    }//GEN-LAST:event_volverHistoriaButtonActionPerformed

    /**
     * al precionar el boton "actualizar" llama al metodo actualizar().
     * 
     * @param evt 
     */
    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_actualizarActionPerformed

    
    /**
     * cuando se abre la ventana actualiza el contenido de la pantalla.
     * 
     * @param evt 
     */
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        actualizar();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudiosClinicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudiosClinicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudiosClinicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudiosClinicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudiosClinicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InicioMedButton;
    private javax.swing.JButton PacientesMedButton;
    private javax.swing.JToggleButton actualizar;
    private javax.swing.JButton agregarEstudioButton;
    private javax.swing.JButton cerrarsesionbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton triagesButton;
    private javax.swing.JButton volverHistoriaButton;
    // End of variables declaration//GEN-END:variables
}
