package edu.tallerpoo.gui;

import edu.tallerpoo.data.LogicaAdministrativos;
import edu.tallerpoo.model.Administrativo;
import edu.tallerpoo.model.Gestor;

/**
 *
 * Clase de la pantalla de inicio de los gestores
 */
public class Gestores extends javax.swing.JFrame {

    
    private Gestor gestor;
    /**
     * Creates new form Gestores
     */
    public Gestores() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Metodo que crea el objeto gestor y permite que persista a traves de las ventanas.
     * 
     * @param ges {@link Administrativo}-Gestor que hizo login
     */
    public void setData(Administrativo ges){
        LogicaAdministrativos logic = new LogicaAdministrativos();
        this.gestor = logic.setGestor(ges);
        System.out.println(gestor.toString());
    }
    
    /**
     * Metodo que permite que el gestor que se logueo persista a traves de las ventanas.
     * 
     * @param ges {@link Gestor}-Gestor que hizo login
     */
    public void setData(Gestor ges){
        this.gestor = ges;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cerrarsesionbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        inicioButton = new javax.swing.JButton();
        InfoMedicoButton = new javax.swing.JButton();
        pacientesRecButton = new javax.swing.JButton();
        pacientesAtendidosButton = new javax.swing.JButton();
        infoPorTriagesButton = new javax.swing.JButton();
        triagesCambiadosButton = new javax.swing.JButton();
        medicosMasActivosButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        jPanel2.setBackground(new java.awt.Color(100, 204, 197));

        jLabel1.setBackground(new java.awt.Color(100, 204, 197));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital Delicia Concepcion Masvernat");

        cerrarsesionbtn.setBackground(new java.awt.Color(5, 59, 80));
        cerrarsesionbtn.setForeground(new java.awt.Color(255, 255, 255));
        cerrarsesionbtn.setText("Cerrar Sesion");
        cerrarsesionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 590, Short.MAX_VALUE)
                .addComponent(cerrarsesionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cerrarsesionbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(23, 107, 135));

        inicioButton.setBackground(new java.awt.Color(5, 59, 80));
        inicioButton.setForeground(new java.awt.Color(255, 255, 255));
        inicioButton.setText("Inicio");
        inicioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioButtonActionPerformed(evt);
            }
        });

        InfoMedicoButton.setBackground(new java.awt.Color(5, 59, 80));
        InfoMedicoButton.setForeground(new java.awt.Color(255, 255, 255));
        InfoMedicoButton.setText("Informacion por Medico");
        InfoMedicoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoMedicoButtonActionPerformed(evt);
            }
        });

        pacientesRecButton.setBackground(new java.awt.Color(5, 59, 80));
        pacientesRecButton.setForeground(new java.awt.Color(255, 255, 255));
        pacientesRecButton.setText("Pacientes Recurrentes");
        pacientesRecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesRecButtonActionPerformed(evt);
            }
        });

        pacientesAtendidosButton.setBackground(new java.awt.Color(5, 59, 80));
        pacientesAtendidosButton.setForeground(new java.awt.Color(255, 255, 255));
        pacientesAtendidosButton.setText("Pacientes Atendidos");
        pacientesAtendidosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesAtendidosButtonActionPerformed(evt);
            }
        });

        infoPorTriagesButton.setBackground(new java.awt.Color(5, 59, 80));
        infoPorTriagesButton.setForeground(new java.awt.Color(255, 255, 255));
        infoPorTriagesButton.setText("Informacion de Triages");
        infoPorTriagesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoPorTriagesButtonActionPerformed(evt);
            }
        });

        triagesCambiadosButton.setBackground(new java.awt.Color(5, 59, 80));
        triagesCambiadosButton.setForeground(new java.awt.Color(255, 255, 255));
        triagesCambiadosButton.setText("Triages Cambiados");
        triagesCambiadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triagesCambiadosButtonActionPerformed(evt);
            }
        });

        medicosMasActivosButton.setBackground(new java.awt.Color(5, 59, 80));
        medicosMasActivosButton.setForeground(new java.awt.Color(255, 255, 255));
        medicosMasActivosButton.setText("Medicos mas Activos");
        medicosMasActivosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicosMasActivosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InfoMedicoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
            .addComponent(pacientesRecButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pacientesAtendidosButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(medicosMasActivosButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoPorTriagesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(triagesCambiadosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(inicioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(InfoMedicoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pacientesRecButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pacientesAtendidosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(medicosMasActivosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(infoPorTriagesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(triagesCambiadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 224, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bienvenido - (funcionario/gestor)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * al precionar el boton "cerrar sesion" Este metodo cierra la pantalla acutal y muestra la del login
     * @param evt 
     */
    private void cerrarsesionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionbtnActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        gestor = null;
    }//GEN-LAST:event_cerrarsesionbtnActionPerformed

    /**
     * al precionar el boton "Pacientes Recurrentes" Este metodo cierra la pantalla actual y muestra la de los pacientes mas recurrentes en un rango de fechas
     * @param evt 
     */
    private void pacientesRecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesRecButtonActionPerformed
        this.dispose();
        PacientesRecurrentesGestores r1 = new PacientesRecurrentesGestores();
        r1.setData(gestor);
        r1.setVisible(true);
        r1.setLocationRelativeTo(null);
    }//GEN-LAST:event_pacientesRecButtonActionPerformed

    /**
     * al precionar el boton "Informacion por Medico" Este metodo cierra la pantalla actual y muestra la de la cantidad de pacientes atendidos por un medico en un rango de fechas
     * @param evt 
     */
    private void InfoMedicoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoMedicoButtonActionPerformed
        this.dispose();
        InformacionMedicoGestores g1 = new InformacionMedicoGestores();
        g1.setData(gestor);
        g1.setVisible(true);
        g1.setLocationRelativeTo(null);
    }//GEN-LAST:event_InfoMedicoButtonActionPerformed

    /**
     * al precionar el boton "Pacientes Atendidos" Este metodo cierra la pantalla actual y muestra la de los pacientes atendidos es un rango de fechas dadas
     * @param evt 
     */
    private void pacientesAtendidosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesAtendidosButtonActionPerformed
        this.dispose();
        PacientesAtendidosGestores a1 = new PacientesAtendidosGestores();
        a1.setData(gestor);
        a1.setVisible(true);
        a1.setLocationRelativeTo(null);
    }//GEN-LAST:event_pacientesAtendidosButtonActionPerformed

    /**
     * al precionar el boton "Medicos mas Activos" Este metodo cierra la ventana actual y abre la que muestra el medico que mas pacientes atendio en
     * un rango de fechas dadas
     * @param evt 
     */
    private void medicosMasActivosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicosMasActivosButtonActionPerformed
        this.dispose();
        MedicosActivosGestores m1 = new MedicosActivosGestores();
        m1.setData(gestor);
        m1.setVisible(true);
        m1.setLocationRelativeTo(null);
    }//GEN-LAST:event_medicosMasActivosButtonActionPerformed
    
    /**
     * al precionar el boton "Informacion de Triages" Este metodo cierra la ventana acutal y abre la que muestra la cantidad de triages realizados
     * en un rango de fechas dadas
     * @param evt 
     */
    private void infoPorTriagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoPorTriagesButtonActionPerformed
        this.dispose();
        InformacionTriagesGestores t1 = new InformacionTriagesGestores();
        t1.setData(gestor);
        t1.setVisible(true);
        t1.setLocationRelativeTo(null);
    }//GEN-LAST:event_infoPorTriagesButtonActionPerformed

    /**
     * al precionar el boton "Triages Cambiados" Este metodo cuerra la ventana acutal y muestra la de los triages que fueron cambiados por
     * por algun funcionario autorizado
     * @param evt 
     */
    private void triagesCambiadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triagesCambiadosButtonActionPerformed
        this.dispose();
        TriagesCambiadosGestores t2 = new TriagesCambiadosGestores();
        t2.setData(gestor);
        t2.setVisible(true);
        t2.setLocationRelativeTo(null);
    }//GEN-LAST:event_triagesCambiadosButtonActionPerformed

    /**
     * Este metodo edita el texto de bienvenida para mostrar el nombre del administrador que hizo login
     * 
     * @param evt 
     */
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        jLabel2.setText("Bienvenido - " + gestor.getNombre() + " " + gestor.getApellido());
    }//GEN-LAST:event_formComponentShown

    private void inicioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfoMedicoButton;
    private javax.swing.JButton cerrarsesionbtn;
    private javax.swing.JButton infoPorTriagesButton;
    private javax.swing.JButton inicioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton medicosMasActivosButton;
    private javax.swing.JButton pacientesAtendidosButton;
    private javax.swing.JButton pacientesRecButton;
    private javax.swing.JButton triagesCambiadosButton;
    // End of variables declaration//GEN-END:variables
}
