
package edu.tallerpoo.gui;

import edu.tallerpoo.data.LogicaRegistro;
import edu.tallerpoo.data.Utilidades;
import edu.tallerpoo.model.Medico;
import edu.tallerpoo.model.Registro;
import edu.tallerpoo.model.tipoEstado;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 * Clase de medico que muestra los pacientes que no fuereon atendidos.
 * 
 */
public class Pacientes extends javax.swing.JFrame {

    /**
     * Creates new form Pacientes
     */
    private Medico medic;
    
    public Pacientes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * metodo que actualiza el contenido de la tabla que se muestra por pantalla
     * 
     */
    public void actualizar(){   
        LogicaRegistro r=new LogicaRegistro();
        ArrayList<Registro>registro=new ArrayList();

        registro=r.leerRegistro();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        Utilidades u=new Utilidades();
        for(Registro p : registro){
            if((p.getEstado()==tipoEstado.Atendido)||(p.getEstado()==tipoEstado.Procesado)){
              continue;  
            }else{
            String [] array={Integer.toString(p.getPaciente().getDocumento()),Integer.toString(p.getId()),p.getPaciente().getNombre(),p.getPaciente().getApellido(),p.getMotivo(),Utilidades.convertDate(p.getFecha()),Utilidades.convertHora(p.getHora())};
            model.addRow(array); 
            }
        }
    }
    
     /**
     * Metodo que permite que el medico que se logueo persista a traves de las ventanas.
     * 
     * @param medic {@link Medico}-Medico que hizo login
     */
    public void setData(Medico medic){
        this.medic = medic;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cerrarsesionbtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        inicioButton = new javax.swing.JButton();
        pacientesButton = new javax.swing.JButton();
        pacientesAtencionButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        atenderButton = new javax.swing.JButton();
        realizarTriageButton = new javax.swing.JButton();
        cambiarTriageButton = new javax.swing.JButton();
        actualizarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        jPanel2.setBackground(new java.awt.Color(100, 204, 197));

        jLabel1.setBackground(new java.awt.Color(100, 204, 197));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital Delicia Concepcion Masvernat");

        cerrarsesionbtn.setBackground(new java.awt.Color(5, 59, 80));
        cerrarsesionbtn.setForeground(new java.awt.Color(255, 255, 255));
        cerrarsesionbtn.setText("Cerrar Sesion");
        cerrarsesionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarsesionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cerrarsesionbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(23, 107, 135));

        inicioButton.setBackground(new java.awt.Color(5, 59, 80));
        inicioButton.setForeground(new java.awt.Color(255, 255, 255));
        inicioButton.setText("Inicio");
        inicioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioButtonActionPerformed(evt);
            }
        });

        pacientesButton.setBackground(new java.awt.Color(5, 59, 80));
        pacientesButton.setForeground(new java.awt.Color(255, 255, 255));
        pacientesButton.setText("Pacientes");
        pacientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesButtonActionPerformed(evt);
            }
        });

        pacientesAtencionButton.setBackground(new java.awt.Color(5, 59, 80));
        pacientesAtencionButton.setForeground(new java.awt.Color(255, 255, 255));
        pacientesAtencionButton.setText("Pacientes en Atencion");
        pacientesAtencionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesAtencionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pacientesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
            .addComponent(pacientesAtencionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(inicioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pacientesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pacientesAtencionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(23, 107, 135));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(23, 107, 135));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pacientes");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI Paciente", "ID Registro", "Nombre", "Apellido", "Motivo Consulta", "Fecha", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        atenderButton.setBackground(new java.awt.Color(5, 59, 80));
        atenderButton.setForeground(new java.awt.Color(255, 255, 255));
        atenderButton.setText("Atender");
        atenderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderButtonActionPerformed(evt);
            }
        });

        realizarTriageButton.setBackground(new java.awt.Color(5, 59, 80));
        realizarTriageButton.setForeground(new java.awt.Color(255, 255, 255));
        realizarTriageButton.setText("Realizar Triage");
        realizarTriageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarTriageButtonActionPerformed(evt);
            }
        });

        cambiarTriageButton.setBackground(new java.awt.Color(5, 59, 80));
        cambiarTriageButton.setForeground(new java.awt.Color(255, 255, 255));
        cambiarTriageButton.setText("Cambiar Triage");
        cambiarTriageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarTriageButtonActionPerformed(evt);
            }
        });

        actualizarButton.setBackground(new java.awt.Color(5, 59, 80));
        actualizarButton.setForeground(new java.awt.Color(255, 255, 255));
        actualizarButton.setText("Actualizar");
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(atenderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(realizarTriageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(cambiarTriageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(actualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atenderButton)
                            .addComponent(realizarTriageButton)
                            .addComponent(cambiarTriageButton)
                            .addComponent(actualizarButton))
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * al precionar el boton "Cerrar sesion" esta ventana se cierra y abre la del login
     * @param evt 
     */
    private void cerrarsesionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionbtnActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        medic = null;
    }//GEN-LAST:event_cerrarsesionbtnActionPerformed

    /**
     * al precionar el boton "Inicio" esta ventana se cierra y abre la principal de medico.
     * 
     * @param evt 
     */
    private void inicioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioButtonActionPerformed
        this.dispose();
        MedicoGUI m1 = new MedicoGUI();
        m1.setData(medic);
        m1.setVisible(true);
        m1.setLocationRelativeTo(null);
    }//GEN-LAST:event_inicioButtonActionPerformed
   
    /**
     * al precionar el boton "Pacientes" Este metodo cierra la pantalla actual y muestra la de los pacientes que no tienen triage realizado
     * @param evt 
     */
    private void pacientesAtencionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesAtencionButtonActionPerformed
        this.dispose();
        PacientesAtencion p1 = new PacientesAtencion();
        p1.setData(medic);
        p1.setVisible(true);
        p1.setLocationRelativeTo(null);
    }//GEN-LAST:event_pacientesAtencionButtonActionPerformed

    /**
     * cuando se preciona el boton "atender" se le asigna el paciente seleccionado al medico y muestra la ventana para asignarle un box al paciente
     * 
     * @param evt 
     */
    private void atenderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String[] array = new String[model.getColumnCount()];
        LogicaRegistro r=new LogicaRegistro();
        
        
        
        for(int i=0; i<model.getColumnCount()-1; i++){
            array[i] = model.getValueAt(jTable1.getSelectedRow(), i).toString();
        }
        
        Boxes b = new Boxes();
        b.setData(array, this.medic);
        b.setVisible(true);
        b.setLocationRelativeTo(null);
        actualizar();
    }//GEN-LAST:event_atenderButtonActionPerformed

    /**
     * cuando se preciona el boton "realizar triage" abre la ventana para que se le realize este mismo al paciente seleccionado
     * 
     * @param evt 
     */
    private void realizarTriageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarTriageButtonActionPerformed
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       
        Triage2 t2 = new Triage2();
        t2.setIdRegistro(Integer.parseInt(model.getValueAt(jTable1.getSelectedRow(), 1).toString()));
        t2.setVisible(true);
        t2.setLocationRelativeTo(null);
       
        actualizar();
    }//GEN-LAST:event_realizarTriageButtonActionPerformed

    /**
     * cuando se preciona el boton "cambiar triage" abre la ventana para que se le cambie este mismo al paciente seleccionado
     * 
     * @param evt 
     */
    private void cambiarTriageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarTriageButtonActionPerformed
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        String[] paciente = {model.getValueAt(jTable1.getSelectedRow(), 0).toString(),
            model.getValueAt(jTable1.getSelectedRow(), 2).toString(),model.getValueAt(jTable1.getSelectedRow(), 3).toString()
        ,model.getValueAt(jTable1.getSelectedRow(), 1).toString()};
        CambiarTriage ct = new CambiarTriage();
        ct.setPaciente(paciente);
        ct.setVisible(true);
        ct.setLocationRelativeTo(null);
        actualizar();
    }//GEN-LAST:event_cambiarTriageButtonActionPerformed

    private void pacientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesButtonActionPerformed

    }//GEN-LAST:event_pacientesButtonActionPerformed

    /**
     * Al precionar actualizar llama al metodo con este mismo nombre, que muestra el contenido actualizado de la pantalla
     * 
     * @param evt 
     */
    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        
        actualizar();
    }//GEN-LAST:event_actualizarButtonActionPerformed

    /**
     * Cuando se abre la ventana se llama al metodo actualizar para que muestre el contenido en la pantalla
     * 
     * @param evt 
     */
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        actualizar();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarButton;
    private javax.swing.JButton atenderButton;
    private javax.swing.JButton cambiarTriageButton;
    private javax.swing.JButton cerrarsesionbtn;
    private javax.swing.JButton inicioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pacientesAtencionButton;
    private javax.swing.JButton pacientesButton;
    private javax.swing.JButton realizarTriageButton;
    // End of variables declaration//GEN-END:variables
}
