/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.tallerpoo.gui;

import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvValidationException;
import edu.tallerpoo.data.LogicaRegistro;
import edu.tallerpoo.data.Utilidades;
import edu.tallerpoo.model.Medico;
import edu.tallerpoo.model.Registro;
import edu.tallerpoo.model.tipoEstado;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * clase de la pantalla en la que se muestran los pacientes ya atendidos
 */
public class PacientesAtencion extends javax.swing.JFrame {

    private Medico medic;
    private Registro reg;
    /**
     * Creates new form PacientesParaAtender
     */
    public PacientesAtencion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    

    private void actualizar(){
         ArrayList<Registro> reg = LogicaRegistro.leerRegistro();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for(Registro v : reg){
            try {
                if((v.getEstado() == tipoEstado.Atendido) && (checkpoint(this.medic.getDocumento(),v.getPaciente().getDocumento()))){
                    String [] array = {Integer.toString(v.getPaciente().getDocumento()), v.getPaciente().getNombre(), v.getPaciente().getApellido(), Integer.toString(v.getBoxAtencion().getNumeroBox()), null };
                    model.addRow(array);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(PacientesAtencion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * Metodo que permite que el medico que se logueo persista a traves de las ventanas.
     * 
     * @param medic {@link Medico}-Medico que hizo login
     */
    public void setData(Medico medic){
        this.medic = medic;
    }
    
    public void setReg(int dni) throws IOException{
        try {
            this.reg = LogicaRegistro.getUnRegistro(dni);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Boxes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CsvValidationException ex) {
            Logger.getLogger(Boxes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cerrarsesionbtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        inicioButton = new javax.swing.JButton();
        pacientesButton = new javax.swing.JButton();
        pacientesEnAtencionButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        verHistoriaButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nuevoInformeButton = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        FinalizarAtencionButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(238, 238, 238));

        jPanel2.setBackground(new java.awt.Color(100, 204, 197));

        jLabel1.setBackground(new java.awt.Color(100, 204, 197));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital Delicia Concepcion Masvernat");

        cerrarsesionbtn.setBackground(new java.awt.Color(5, 59, 80));
        cerrarsesionbtn.setForeground(new java.awt.Color(255, 255, 255));
        cerrarsesionbtn.setText("Cerrar Sesion");
        cerrarsesionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarsesionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cerrarsesionbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(23, 107, 135));

        inicioButton.setBackground(new java.awt.Color(5, 59, 80));
        inicioButton.setForeground(new java.awt.Color(255, 255, 255));
        inicioButton.setText("Inicio");
        inicioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioButtonActionPerformed(evt);
            }
        });

        pacientesButton.setBackground(new java.awt.Color(5, 59, 80));
        pacientesButton.setForeground(new java.awt.Color(255, 255, 255));
        pacientesButton.setText("Pacientes");
        pacientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesButtonActionPerformed(evt);
            }
        });

        pacientesEnAtencionButton.setBackground(new java.awt.Color(5, 59, 80));
        pacientesEnAtencionButton.setForeground(new java.awt.Color(255, 255, 255));
        pacientesEnAtencionButton.setText("Pacientes en Atencion");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pacientesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
            .addComponent(pacientesEnAtencionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(inicioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pacientesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pacientesEnAtencionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido", "Box de Atencion", "Informe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Lista de Pacientes");

        verHistoriaButton.setBackground(new java.awt.Color(5, 59, 80));
        verHistoriaButton.setForeground(new java.awt.Color(255, 255, 255));
        verHistoriaButton.setText("Ver Historia Clinica");
        verHistoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verHistoriaButtonActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(23, 107, 135));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(23, 107, 135));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pacientes en Atencion");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        nuevoInformeButton.setBackground(new java.awt.Color(5, 59, 80));
        nuevoInformeButton.setForeground(new java.awt.Color(255, 255, 255));
        nuevoInformeButton.setText("Nuevo Informe");
        nuevoInformeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoInformeButtonActionPerformed(evt);
            }
        });

        Actualizar.setBackground(new java.awt.Color(5, 59, 80));
        Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        FinalizarAtencionButton1.setBackground(new java.awt.Color(5, 59, 80));
        FinalizarAtencionButton1.setForeground(new java.awt.Color(255, 255, 255));
        FinalizarAtencionButton1.setText("Finalizar Atencion");
        FinalizarAtencionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarAtencionButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(verHistoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nuevoInformeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(FinalizarAtencionButton1)
                                .addGap(18, 18, 18)
                                .addComponent(Actualizar)))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(verHistoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoInformeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FinalizarAtencionButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * al precionar el boton "Cerrar sesion" esta ventana se cierra y abre la del login
     * @param evt 
     */
    private void cerrarsesionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionbtnActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        medic = null;
    }//GEN-LAST:event_cerrarsesionbtnActionPerformed

      
    /**
     * al precionar el boton "Pacientes" Este metodo cierra la pantalla actual y muestra la de los pacientes que no tienen triage realizado
     * @param evt 
     */
    private void pacientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesButtonActionPerformed
        this.dispose();
        Pacientes t1 = new Pacientes();
        t1.setData(medic);
        t1.setVisible(true);
        t1.setLocationRelativeTo(null);
    }//GEN-LAST:event_pacientesButtonActionPerformed

    /**
     * al precionar "Ver Historia Clinica" Este metodo cierra la pantalla actual y abre la historia clinica del paciente seleccionado
     * 
     * @param evt 
     */
    private void verHistoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verHistoriaButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String[] array = new String[model.getColumnCount()];
        
        for(int i=0; i<model.getColumnCount()-1; i++){
            array[i] = model.getValueAt(jTable1.getSelectedRow(), i).toString();
        }
        
        
        this.dispose();
        HistoriaClinicaPaciente hp = new HistoriaClinicaPaciente();
        hp.setData(array);
        hp.setVisible(true);
        hp.setLocationRelativeTo(null);
    }//GEN-LAST:event_verHistoriaButtonActionPerformed

    /**
     * al precionar el boton "Inicio" Este metodo cierra la pantalla acutal y abre a la principar del medico
     * @param evt 
     */
    private void inicioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioButtonActionPerformed
        this.dispose();
        MedicoGUI m1 = new MedicoGUI();
        m1.setData(medic);
        m1.setVisible(true);
        m1.setLocationRelativeTo(null);
    }//GEN-LAST:event_inicioButtonActionPerformed
    
    /**
     * al precionar "Nuevo Informe" este metodo abre la ventana que se utiliza para crear nuevos informes
     * @param evt 
     */
    private void nuevoInformeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoInformeButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String[] array = new String[model.getColumnCount()];
        LogicaRegistro r=new LogicaRegistro();
        
        for(int i=0; i<model.getColumnCount()-1; i++){
            array[i] = model.getValueAt(jTable1.getSelectedRow(), i).toString();
        }
   
        Informes i = new Informes();
        i.setData(array);
        i.setVisible(true);
        i.setLocationRelativeTo(null);
    }//GEN-LAST:event_nuevoInformeButtonActionPerformed

    /**
     * Al precionar "acutalizar" llama al metodo con el mismo nombre
     * @param evt 
     */
    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_ActualizarActionPerformed

    /**
     * recive el dni del paciente y del medico para ver si este puede atenderlo
     * 
     * @param dni          {@link Integer}-DNI del medico que hizo login
     * @param dnipaciente  {@link Integer}-DNI del paciente 
     * @return             {@link Boolean}-"true" si el dni del medico esta asociado al del paciente, "false" en caso contrario
     * @throws FileNotFoundException 
     */
    private boolean checkpoint(int dni,int dnipaciente) throws FileNotFoundException{
        CSVReader reader = new CSVReader(new FileReader(Utilidades.rutaBox()));
        
        String[] rows;
        try {
            reader.readNext();
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(PacientesAtencion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while((rows = reader.readNext()) != null){
                if(dni==Integer.parseInt(rows[3])&&dnipaciente==Integer.parseInt(rows[2])){
                    return true;
                }
            }
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(PacientesAtencion.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
    
    /**
     * al precionar el boton "finalizar atencion" se abre la ventana de NuevaHistoriaClinica para hacercela al paciente seleccionado
     * 
     * @param evt 
     */
    private void FinalizarAtencionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarAtencionButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String[] array = new String[model.getColumnCount()];
        LogicaRegistro r=new LogicaRegistro();
        
        for(int i=0; i<model.getColumnCount()-1; i++){
            array[i] = model.getValueAt(jTable1.getSelectedRow(), i).toString();
        }
        

        NuevaHistoriaClinica nhc=new NuevaHistoriaClinica();
        nhc.setData(array, this.medic);
        nhc.setLocationRelativeTo(null);
        nhc.setVisible(true);
        actualizar();
    }//GEN-LAST:event_FinalizarAtencionButton1ActionPerformed

    /**
     * Cuando se muestra la ventana llama a la funcion actualizar
     * 
     * @param evt 
     */
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       actualizar();
    }//GEN-LAST:event_formComponentShown

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacientesAtencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacientesAtencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacientesAtencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacientesAtencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacientesAtencion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton FinalizarAtencionButton1;
    private javax.swing.JButton cerrarsesionbtn;
    private javax.swing.JButton inicioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nuevoInformeButton;
    private javax.swing.JButton pacientesButton;
    private javax.swing.JButton pacientesEnAtencionButton;
    private javax.swing.JButton verHistoriaButton;
    // End of variables declaration//GEN-END:variables
}
