package edu.tallerpoo.gui;

import edu.tallerpoo.data.LogicaEstadisticas;
import edu.tallerpoo.model.Gestor;
import java.util.Date;
import javax.swing.table.DefaultTableModel;


public class PacientesRecurrentesGestores extends javax.swing.JFrame {
    private Gestor gestor;

    /**
     * Creates new form PacientesRecurrentesGestoresNew
     */
    public PacientesRecurrentesGestores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cerrarsesionbtn1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        iniciojButton = new javax.swing.JButton();
        infoPorMedButton = new javax.swing.JButton();
        recurrentesButton = new javax.swing.JButton();
        atendidosButton = new javax.swing.JButton();
        infoDeTriageButton = new javax.swing.JButton();
        triageCambiadosButton = new javax.swing.JButton();
        medMasActivosButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fecha2 = new com.toedter.calendar.JDateChooser();
        fecha1 = new com.toedter.calendar.JDateChooser();
        btnConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(238, 238, 238));

        jPanel4.setBackground(new java.awt.Color(100, 204, 197));

        jLabel2.setBackground(new java.awt.Color(100, 204, 197));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hospital Delicia Concepcion Masvernat");

        cerrarsesionbtn1.setBackground(new java.awt.Color(5, 59, 80));
        cerrarsesionbtn1.setForeground(new java.awt.Color(255, 255, 255));
        cerrarsesionbtn1.setText("Cerrar Sesion");
        cerrarsesionbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarsesionbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cerrarsesionbtn1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(23, 107, 135));

        iniciojButton.setBackground(new java.awt.Color(5, 59, 80));
        iniciojButton.setForeground(new java.awt.Color(255, 255, 255));
        iniciojButton.setText("Inicio");
        iniciojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciojButtonActionPerformed(evt);
            }
        });

        infoPorMedButton.setBackground(new java.awt.Color(5, 59, 80));
        infoPorMedButton.setForeground(new java.awt.Color(255, 255, 255));
        infoPorMedButton.setText("Informacion por Medico");
        infoPorMedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoPorMedButtonActionPerformed(evt);
            }
        });

        recurrentesButton.setBackground(new java.awt.Color(5, 59, 80));
        recurrentesButton.setForeground(new java.awt.Color(255, 255, 255));
        recurrentesButton.setText("Pacientes Recurrentes");

        atendidosButton.setBackground(new java.awt.Color(5, 59, 80));
        atendidosButton.setForeground(new java.awt.Color(255, 255, 255));
        atendidosButton.setText("Pacientes Atendidos");
        atendidosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atendidosButtonActionPerformed(evt);
            }
        });

        infoDeTriageButton.setBackground(new java.awt.Color(5, 59, 80));
        infoDeTriageButton.setForeground(new java.awt.Color(255, 255, 255));
        infoDeTriageButton.setText("Informacion de Triages");
        infoDeTriageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoDeTriageButtonActionPerformed(evt);
            }
        });

        triageCambiadosButton.setBackground(new java.awt.Color(5, 59, 80));
        triageCambiadosButton.setForeground(new java.awt.Color(255, 255, 255));
        triageCambiadosButton.setText("Triages Cambiados");
        triageCambiadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triageCambiadosButtonActionPerformed(evt);
            }
        });

        medMasActivosButton.setBackground(new java.awt.Color(5, 59, 80));
        medMasActivosButton.setForeground(new java.awt.Color(255, 255, 255));
        medMasActivosButton.setText("Medicos mas Activos");
        medMasActivosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medMasActivosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciojButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoPorMedButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
            .addComponent(recurrentesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(atendidosButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(medMasActivosButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoDeTriageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(triageCambiadosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(iniciojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(infoPorMedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(recurrentesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(atendidosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(medMasActivosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(infoDeTriageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(triageCambiadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 276, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(23, 107, 135));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(23, 107, 135));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pacientes Recurrentes");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Pacientes mas recurrentes en un rango de fechas");

        jLabel5.setBackground(new java.awt.Color(238, 238, 238));
        jLabel5.setText("Fecha mas antigua");

        jLabel6.setBackground(new java.awt.Color(238, 238, 238));
        jLabel6.setText("Fecha mas reciente");

        fecha2.setBackground(new java.awt.Color(238, 238, 238));

        fecha1.setBackground(new java.awt.Color(238, 238, 238));

        btnConsulta.setText("Consultar");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Nombre", "Cantidad de visitas"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(btnConsulta)))
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(jLabel4)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8)
                                .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(btnConsulta))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * al precionar el boton "cerrar sesion" Este metodo cierra la pantalla acutal y muestra la del login
     * @param evt 
     */
    private void cerrarsesionbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionbtn1ActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        gestor = null;
    }//GEN-LAST:event_cerrarsesionbtn1ActionPerformed

    /**
     * al precionar el boton "Inicio" Este metodo cierra la pantalla actual y muestra la principal de gestores
     * @param evt 
     */
    private void iniciojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciojButtonActionPerformed
        this.dispose();
        Gestores inicio = new Gestores();
        inicio.setData(gestor);
        inicio.setVisible(true);
        inicio.setLocationRelativeTo(null);
    }//GEN-LAST:event_iniciojButtonActionPerformed

    /**
     * al precionar el boton "Informacion por Medico" Este metodo cierra la pantalla actual y muestra la de la cantidad de pacientes atendidos por un medico en un rango de fechas
     * @param evt 
     */
    private void infoPorMedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoPorMedButtonActionPerformed
        this.dispose();
        InformacionMedicoGestores m1 = new InformacionMedicoGestores();
        m1.setData(gestor);
        m1.setVisible(true);
        m1.setLocationRelativeTo(null);
    }//GEN-LAST:event_infoPorMedButtonActionPerformed

    /**
     * al precionar el boton "Pacientes Atendidos" Este metodo cierra la pantalla actual y muestra la de los pacientes atendidos es un rango de fechas dadas
     * @param evt 
     */
    private void atendidosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atendidosButtonActionPerformed
        this.dispose();
        PacientesAtendidosGestores a1 = new PacientesAtendidosGestores();
        a1.setData(gestor);
        a1.setVisible(true);
        a1.setLocationRelativeTo(null);
    }//GEN-LAST:event_atendidosButtonActionPerformed
    
    /**
     * al precionar el boton "Informacion de Triages" Este metodo cierra la ventana acutal y abre la que muestra la cantidad de triages realizados
     * en un rango de fechas dadas
     * @param evt 
     */
    private void infoDeTriageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoDeTriageButtonActionPerformed
        this.dispose();
        InformacionTriagesGestores t1 = new InformacionTriagesGestores();
        t1.setData(gestor);
        t1.setVisible(true);
        t1.setLocationRelativeTo(null);
    }//GEN-LAST:event_infoDeTriageButtonActionPerformed

    /**
     * al precionar el boton "Triages Cambiados" Este metodo cuerra la ventana acutal y muestra la de los triages que fueron cambiados por
     * por algun funcionario autorizado
     * @param evt 
     */
    private void triageCambiadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triageCambiadosButtonActionPerformed
        this.dispose();
        TriagesCambiadosGestores t2 = new TriagesCambiadosGestores();
        t2.setData(gestor);
        t2.setVisible(true);
        t2.setLocationRelativeTo(null);
    }//GEN-LAST:event_triageCambiadosButtonActionPerformed

    /**
     * al precionar el boton "Medicos mas Activos" Este metodo cierra la ventana actual y abre la que muestra el medico que mas pacientes atendio en
     * un rango de fechas dadas
     * @param evt 
     */
    private void medMasActivosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medMasActivosButtonActionPerformed
        this.dispose();
        MedicosActivosGestores m2 = new MedicosActivosGestores();
        m2.setData(gestor);
        m2.setVisible(true);
        m2.setLocationRelativeTo(null);
    }//GEN-LAST:event_medMasActivosButtonActionPerformed

    /**
     * al precionar el boton consulta, muestra por pantalla los datos de los pacientes mas recurrentes en un rango de fechas
     * 
     * @param evt 
     */
    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        LogicaEstadisticas logica = new LogicaEstadisticas();
        Date f1 = fecha1.getDate();
        Date f2 = fecha2.getDate();
        
        DefaultTableModel model = logica.estadisticaFecha(f1, f2);
        jTable1.setModel(model);;

    }//GEN-LAST:event_btnConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacientesRecurrentesGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacientesRecurrentesGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacientesRecurrentesGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacientesRecurrentesGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacientesRecurrentesGestores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atendidosButton;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton cerrarsesionbtn1;
    private com.toedter.calendar.JDateChooser fecha1;
    private com.toedter.calendar.JDateChooser fecha2;
    private javax.swing.JButton infoDeTriageButton;
    private javax.swing.JButton infoPorMedButton;
    private javax.swing.JButton iniciojButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton medMasActivosButton;
    private javax.swing.JButton recurrentesButton;
    private javax.swing.JButton triageCambiadosButton;
    // End of variables declaration//GEN-END:variables

    public void setData(Gestor gestor) {
        this.gestor=gestor;
    }
}
