/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.tallerpoo.gui;

import edu.tallerpoo.data.LogicaPaciente;
import edu.tallerpoo.data.LogicaRegistro;
import edu.tallerpoo.model.Administrativo;
import edu.tallerpoo.model.Paciente;
import edu.tallerpoo.model.tipoEstCivil;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Agustín Bravo
 */
public class RegistroPaciente extends javax.swing.JFrame {
    private Administrativo administrativo;
    private int documentoExt;
 
    /**
     * Creates new form RegistroPaciente
     */
    public RegistroPaciente() {
        initComponents();
        setLocationRelativeTo(null);
        RegistrarPaciente.setEnabled(false);
        
    }
    
    /**
     * Metodo que permite que el Administrativo que se logueo persista a traves de las ventanas.
     * 
     * @param ad {@link Administrativo}-Administrativo que hizo login
     */
    public void setData(Administrativo ad){
        this.administrativo = ad;
    }
    
    /**
     * Metodo que obtiene el documento de la pantalla de ConsultaPaciente si este no esta registrado
     * 
     * @param doc {@link Integer}-Documento del paciente no registrado
     */
    public void setDoc(int doc){
        this.documentoExt=doc;
        
    }

    /**
     * Este metodo valida que el texto que se ingreso no contenga catacteres numericos ni comas.
     * 
     * @param txt {@link String}-Texto el cual sera validado
     * 
     * @return {@link Boolean}-True si no contiene ningun numero y/o coma. False en caso contrario
     */
    public boolean validarTxt(String txt){
        boolean res;
        if(txt.isEmpty() || !txt.matches("^[^0-9+,.-]+$")) {
            res = false;
        }else{
            res = true;
    }
        return res;
    }
    
    /**
     * Este metodo valida que el numero que se ingreso no contenga letras y/o comas.
     * 
     * @param num {@link String}-String el cual sera validado
     * 
     * @return {@link Boolean}-True si no contiene ninguna letra y/o coma. False en caso contrario
     */
    public boolean validarNum(String num){
        boolean res;
        if(num.isEmpty() || !num.matches("^[^A-Za-z+,.-]+$")) {
            res = false;
        }else{
            res = true;
        }
        return res;
    }
        
    /**
     *  Este metodo valida si todos los parametros ingresados por teclado son validos
     *  en caso de serlos habilita el boton para registrar el funcionario
     *
     */
    public void validar() {
    boolean domicilioValido,emailValido,fechaValido,direcpcontValido=false;
    // Validación del campo nombre
    
    boolean nombreValido = validarTxt(nombreTextField.getText());

    boolean apellidoValido = validarTxt(apellidoTextField.getText());
    
    if(domicilioTextField.getText().isEmpty()) {
        domicilioValido = false;
    }else{
        domicilioValido = true;
    }
    
    boolean documentoValido = validarNum(documentoTextField.getText());
    
    boolean celularValido = validarNum(celularTextField.getText());
    
    
    if(emailTextField.getText().isEmpty() || !emailTextField.getText().matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
        emailValido = false;
    }else{
        emailValido = true;
    }

    if(FechaNacimiento.equals("")) {
        fechaValido = false;
    }else{
        fechaValido = true;
    }
    
    
    boolean nombrepcontValido=validarTxt(nombrePersonaTextField.getText());
    
    if(domicilioPersonaTextField.getText().isEmpty()) {
        direcpcontValido = false;
    }else{
        direcpcontValido = true;
    }

    boolean celupcontValido=validarNum(celularPersonaTextField1.getText());
 
    
    
    RegistrarPaciente.setEnabled(nombreValido && apellidoValido && domicilioValido && documentoValido && celularValido && emailValido && fechaValido && nombrepcontValido && direcpcontValido && celupcontValido );
}

    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cerrarsesionbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        apellidoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefonofijoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        celularTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nombrePersonaTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        domicilioTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        documentoTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sexoComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        domicilioPersonaTextField = new javax.swing.JTextField();
        FechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        RegistrarPaciente = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        celularPersonaTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        estadocivilComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MotivoConsulta = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(1040, 570));

        jPanel2.setBackground(new java.awt.Color(100, 204, 197));

        jLabel1.setBackground(new java.awt.Color(100, 204, 197));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital Delicia Concepcion Masvernat");

        cerrarsesionbtn.setBackground(new java.awt.Color(5, 59, 80));
        cerrarsesionbtn.setForeground(new java.awt.Color(255, 255, 255));
        cerrarsesionbtn.setText("Cerrar Sesion");
        cerrarsesionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarsesionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cerrarsesionbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(238, 238, 238));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        nombreTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreTextFieldKeyReleased(evt);
            }
        });

        apellidoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                apellidoTextFieldKeyReleased(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(238, 238, 238));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Apellido");

        jLabel5.setBackground(new java.awt.Color(238, 238, 238));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Telefono Fijo");

        celularTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                celularTextFieldKeyReleased(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(238, 238, 238));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Celular");

        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyReleased(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(238, 238, 238));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Correo Electronico");

        nombrePersonaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombrePersonaTextFieldKeyReleased(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(238, 238, 238));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Nombre Completo - Persona de Contacto");

        jLabel9.setBackground(new java.awt.Color(238, 238, 238));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Domicilio");

        domicilioTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                domicilioTextFieldKeyReleased(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(238, 238, 238));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Documento");

        documentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoTextFieldActionPerformed(evt);
            }
        });
        documentoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                documentoTextFieldKeyReleased(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(238, 238, 238));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Sexo");

        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "X" }));
        sexoComboBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sexoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoComboBoxActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(238, 238, 238));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Domicilio - Persona de Contacto");

        domicilioPersonaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domicilioPersonaTextFieldActionPerformed(evt);
            }
        });
        domicilioPersonaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                domicilioPersonaTextFieldKeyReleased(evt);
            }
        });

        FechaNacimiento.setBackground(new java.awt.Color(238, 238, 238));
        FechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FechaNacimiento.setMaxSelectableDate(new Date());
        FechaNacimiento.setMinSelectableDate(new java.util.Date(-2208969686000L));
        FechaNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FechaNacimientoKeyReleased(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(238, 238, 238));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Fecha de Nacimiento");

        RegistrarPaciente.setBackground(new java.awt.Color(5, 59, 80));
        RegistrarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarPaciente.setText("Registrar Paciente");
        RegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarPacienteActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(238, 238, 238));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Celular - Persona de Contacto");

        celularPersonaTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                celularPersonaTextField1KeyReleased(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(23, 107, 135));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(23, 107, 135));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro de Paciente");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(401, 401, 401))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        estadocivilComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado", "Viudo" }));
        estadocivilComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadocivilComboBox1ActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(238, 238, 238));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Estado Civil");

        jLabel16.setBackground(new java.awt.Color(238, 238, 238));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Motivo de Consulta");

        jScrollPane1.setViewportView(MotivoConsulta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegistrarPaciente)
                .addGap(443, 443, 443))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTextField)
                    .addComponent(domicilioTextField)
                    .addComponent(celularTextField)
                    .addComponent(FechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(telefonofijoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(domicilioPersonaTextField)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(estadocivilComboBox1, 0, 228, Short.MAX_VALUE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sexoComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(apellidoTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(documentoTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(celularPersonaTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))
                        .addGap(158, 158, 158))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombrePersonaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(documentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadocivilComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(nombrePersonaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(domicilioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(celularTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonofijoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celularPersonaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(domicilioPersonaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * al precionar el boton "cerrar sesion" Este metodo te cierra la pantalla actual y mustra la del Login
     * 
     * @param evt {@link java.awt.event.ActionEvent}
     */
    private void cerrarsesionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionbtnActionPerformed
        this.dispose();
        Login nombre=new Login();
        nombre.setVisible(true);
        administrativo = null;
    }//GEN-LAST:event_cerrarsesionbtnActionPerformed

    
    /**
     * al precionar el boton "Registrar paciente" este metodo genera un paciente con todos sus parametros cargados y lo envia para confirmacion
     * 
     * @param evt {@link java.awt.event.ActionEvent}
     */
    private void RegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarPacienteActionPerformed
        Paciente p=new Paciente();

        
        String nombre=nombreTextField.getText();
        p.setNombre(nombre);
        
        String apellido=apellidoTextField.getText();
        p.setApellido(apellido);
        
        Date fechaNacimiento = FechaNacimiento.getDate();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
        String FechaString = formatoFecha.format(fechaNacimiento);
        
        
        p.setFechaNac(fechaNacimiento);
        
        String domicilio=domicilioTextField.getText();
        p.setDomicilio(domicilio);
                
        String Documento=documentoTextField.getText();

        
        String TelFijo=telefonofijoTextField.getText();
        p.setTelFijo(TelFijo);
        
        String Celular=celularTextField.getText();
        p.setCelular(Celular);
        
        String EstadoCivil = (String) estadocivilComboBox1.getSelectedItem();
            switch (EstadoCivil){
            case "Casado":
                p.setEstadoCivil(tipoEstCivil.Casado);
                break;
            case "Divorciado":
                p.setEstadoCivil(tipoEstCivil.Divorciado);
                break;
            case "Soltero":
                p.setEstadoCivil(tipoEstCivil.Soltero);
                break;
            case "Viudo":
                p.setEstadoCivil(tipoEstCivil.Viudo);
            }
           
         String tipoSexo=(String)sexoComboBox.getSelectedItem();
         
         String motivoConsulta=MotivoConsulta.getText(); 
        
        String email=emailTextField.getText();
        p.setEmail(email);
        
        String NombrePersonaContacto=nombrePersonaTextField.getText();
        
        String DomicilioPersonaContacto=domicilioPersonaTextField.getText();
        
        String CelularPersonaContacto=celularPersonaTextField1.getText();
        
        String [] ArrayDatos={Documento,nombre,apellido,email,FechaString,TelFijo,Celular,EstadoCivil,domicilio,tipoSexo};
        String []DatosPaciente={Documento,NombrePersonaContacto,DomicilioPersonaContacto,CelularPersonaContacto};
        LogicaRegistro escrituraPaciente=new LogicaRegistro();
        escrituraPaciente.agregarPacientes(ArrayDatos);
        LogicaRegistro escrituraPacienteAlCsvPersonas=new LogicaRegistro();
        escrituraPacienteAlCsvPersonas.agregarPacientes2(DatosPaciente);
        
       
        String [] Persona={Documento, NombrePersonaContacto, DomicilioPersonaContacto, CelularPersonaContacto};   
        LogicaPaciente Escritura=new LogicaPaciente();
        Escritura.escribirCsvRegistroPaciente(Persona);
        
        //Escribe en logicaRegistro el csv Registro con la hora actual que se hizo el registro, motivo y dia
        LogicaRegistro añadirRegistro=new LogicaRegistro();     
        SimpleDateFormat fhora=new SimpleDateFormat("HH:mm");
        Date Hora = new Date();
        SimpleDateFormat fFecha=new SimpleDateFormat("dd-MM-yyyy");
        Date Fecha=new Date();
        String hora=fhora.format(Hora);
        String fecha=fFecha.format(Fecha);  
        añadirRegistro.EscribirRegistro(motivoConsulta,fecha,hora);
        
        
        //--------------------------------------------------------------
        ConsultaPaciente consulta=new ConsultaPaciente();
        consulta.setData(administrativo);
        consulta.setVisible(true);
        consulta.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_RegistrarPacienteActionPerformed

    /**
     * Cada vez que se realiza un cambio en el campo nombre se verifica que sea valido
     * @param evt 
     */
    private void nombreTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTextFieldKeyReleased
        validar();
    }//GEN-LAST:event_nombreTextFieldKeyReleased

    /**
     * Cada vez que se realiza un cambio en el campo apellido se verifica que sea valido
     * @param evt 
     */
    private void apellidoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoTextFieldKeyReleased
        validar();
    }//GEN-LAST:event_apellidoTextFieldKeyReleased

    /**
     * Cada vez que se realiza un cambio en el campo fecha de nacimiento se verifica que sea valido
     * @param evt 
     */
    private void FechaNacimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FechaNacimientoKeyReleased
        validar();
    }//GEN-LAST:event_FechaNacimientoKeyReleased

    /**
     * Cada vez que se realiza un cambio en el campo domicilio se verifica que sea valido
     * @param evt 
     */
    private void domicilioTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_domicilioTextFieldKeyReleased
        validar();
    }//GEN-LAST:event_domicilioTextFieldKeyReleased

    /**
     * Cada vez que se realiza un cambio en el campo documento se verifica que sea valido
     * @param evt 
     */
    private void documentoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_documentoTextFieldKeyReleased
        validar();
    }//GEN-LAST:event_documentoTextFieldKeyReleased

    /**
     * Cada vez que se realiza un cambio en el campo celular se verifica que sea valido
     * @param evt 
     */
    private void celularTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularTextFieldKeyReleased
       validar();
    }//GEN-LAST:event_celularTextFieldKeyReleased

    /**
     * Cada vez que se realiza un cambio en el campo email se verifica que sea valido
     * @param evt 
     */
    private void emailTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyReleased
       validar();
    }//GEN-LAST:event_emailTextFieldKeyReleased

    /**
     * Cada vez que se realiza un cambio en el campo nombre persona de contacto se verifica que sea valido
     * @param evt 
     */
    private void nombrePersonaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrePersonaTextFieldKeyReleased
       validar();
    }//GEN-LAST:event_nombrePersonaTextFieldKeyReleased

    /**
     * Cada vez que se realiza un cambio en el campo domicilio persona de contacto se verifica que sea valido
     * @param evt 
     */
    private void domicilioPersonaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_domicilioPersonaTextFieldKeyReleased
      validar();
    }//GEN-LAST:event_domicilioPersonaTextFieldKeyReleased

    /**
     * Cada vez que se realiza un cambio en el campo nombre celular de contacto se verifica que sea valido
     * @param evt 
     */
    private void celularPersonaTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularPersonaTextField1KeyReleased
      validar();
    }//GEN-LAST:event_celularPersonaTextField1KeyReleased

    /**
     * Cada vez que se realiza un cambio en el campo sexo se verifica que sea valido
     * @param evt 
     */
    private void sexoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoComboBoxActionPerformed
        validar();
    }//GEN-LAST:event_sexoComboBoxActionPerformed

    /**
     * Cada vez que se realiza un cambio en el campo estado civil se verifica que sea valido
     * @param evt 
     */
    private void estadocivilComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadocivilComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadocivilComboBox1ActionPerformed

    private void documentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoTextFieldActionPerformed

    /**
     * cuando se muestra la pantalla se setea el campo documento, con el que se ingreso la pantalla anterior
     * 
     * @param evt 
     */
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        documentoTextField.setText(Integer.toString(documentoExt));
    }//GEN-LAST:event_formComponentShown

    private void domicilioPersonaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domicilioPersonaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domicilioPersonaTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */ 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaNacimiento;
    private javax.swing.JTextPane MotivoConsulta;
    private javax.swing.JButton RegistrarPaciente;
    private javax.swing.JTextField apellidoTextField;
    private javax.swing.JTextField celularPersonaTextField1;
    private javax.swing.JTextField celularTextField;
    private javax.swing.JButton cerrarsesionbtn;
    private javax.swing.JTextField documentoTextField;
    private javax.swing.JTextField domicilioPersonaTextField;
    private javax.swing.JTextField domicilioTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JComboBox<String> estadocivilComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombrePersonaTextField;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JComboBox<String> sexoComboBox;
    private javax.swing.JTextField telefonofijoTextField;
    // End of variables declaration//GEN-END:variables
}
